version: $VERSION
services:
  proxy:
    image: ubuntu/squid:latest
    hostname: proxy
    container_name: proxy
    ports:
      - "3128:3128"
    volumes:
      # ./squid.conf works in osx but not in linux
      - ${PWD}/apps/squid_proxy/squid.conf:/etc/squid/squid.conf
    restart: always
    networks:
      - web
      - no_internet