version: "3.8"
services:
  proxy:
    image: ubuntu/squid:latest
    hostname: proxy
    container_name: proxy
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
    restart: always
    networks:
      - web
      - no_internet