# https://docs.paperless-ngx.com/setup/#docker
# https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.sqlite.yml
# SQLite is used as the database. The SQLite file is stored in the data volume.

services:

  paperless_ngx_broker:
    image: docker.io/library/redis:8-alpine
    container_name: paperless_ngx_broker
    restart: $RESTART
    volumes:
      - $APP_DATA_DIR/paperless_ngx/redis:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - no_internet

  paperless_ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.14.7
    container_name: paperless_ngx
    restart: $RESTART
    depends_on:
      - paperless_ngx_broker
      - paperless_ngx_gotenberg
      - paperless_ngx_tika
#    ports:
#      - "8000:8000"
    volumes:
      - $APP_DATA_DIR/paperless_ngx/data:/usr/src/paperless/data
      - $APP_DATA_DIR/paperless_ngx/media:/usr/src/paperless/media
      - $APP_DATA_DIR/paperless_ngx/export:/usr/src/paperless/export
      - $APP_DATA_DIR/paperless_ngx/consume:/usr/src/paperless/consume
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      PAPERLESS_REDIS: redis://paperless_ngx_broker:6379

      # Tika and Gotenberg for Office document support (Word, Excel, PowerPoint, etc.)
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless_ngx_gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless_ngx_tika:9998

      PAPERLESS_URL: $HTTP_SCHEMA://paperless.$DOMAINNAME
      PAPERLESS_ADMIN_USER: $ADMIN_USER_GLOBAL
      PAPERLESS_ADMIN_PASSWORD: $ADMIN_PASS_GLOBAL

    networks:
      - no_internet
    labels:

      - "homepage.group=Services"
      - "homepage.name=Paperless-ngx"
      - "homepage.icon=paperless-ngx.png"  # https://github.com/walkxcode/dashboard-icons
      - "homepage.href=$HTTP_SCHEMA://paperless.$DOMAINNAME/"
      - "homepage.description=document management"

      - "traefik.enable=true"
      - "traefik.http.routers.paperless.service=paperless"
      - "traefik.http.routers.paperless.rule=Host(`paperless.$DOMAINNAME`)"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"

  paperless_ngx_gotenberg:
    image: docker.io/gotenberg/gotenberg:8.25
    container_name: paperless_ngx_gotenberg
    restart: $RESTART
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - no_internet

  paperless_ngx_tika:
    image: docker.io/apache/tika:3.2.3.0
    container_name: paperless_ngx_tika
    restart: $RESTART
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - no_internet
