services:
  homepage:
      image: ghcr.io/gethomepage/homepage:v0.10.9
      container_name: homepage
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - ${PWD}/apps/homepage/config:/app/config
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
#      ports:
#          - 3000:3000
      restart: $RESTART
      environment:
        - HOMEPAGE_ALLOWED_HOSTS=*
      labels:
          - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      networks:
        - no_internet
