version: $VERSION

services:
  homepage:
      image: ghcr.io/benphelps/homepage:v0.6.7
      container_name: homepage
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "${PWD}/apps/homepage/config:/app/config"
#      ports:
#          - 3000:3000
      restart: $RESTART
      labels:
          - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      networks:
        - no_internet
