
services:
  vaultwarden:
    image: vaultwarden/server:1.33.2-alpine
    container_name: vaultwarden
    restart: always
    volumes:
      - $APP_DATA_DIR/vaultwarden:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
      - SIGNUPS_ALLOWED=true
      - WEBSOCKET_ENABLED=false
      - ADMIN_TOKEN=$ADMIN_PASS_GLOBAL
    networks:
      - no_internet
    labels:

      - "homepage.group=Services"
      - "homepage.name=Vaultwarden"
      - "homepage.icon=bitwarden.png"  # https://github.com/walkxcode/dashboard-icons
      - "homepage.href=$HTTP_SCHEMA://vaultwarden.$DOMAINNAME/"
      - "homepage.description=password manager"

      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.service=vaultwarden"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.$DOMAINNAME`)"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

#      # websocket
#      - "traefik.http.routers.bitwarden-ws.entrypoints=https"
#      - "traefik.http.routers.bitwarden-ws.rule=Host(`bw.sslfor.fun`) && Path(`/notifications/hub`)"
#      - "traefik.http.middlewares.bitwarden-ws=bw-stripPrefix@file"
#      - "traefik.http.middlewares.bitwarden-ws=secureHeaders@file"
#      - "traefik.http.routers.bitwarden-ws.tls=true"
#      - "traefik.http.routers.bitwarden-ws.tls.certresolver=letsencrypt"
#      - "traefik.http.routers.bitwarden-ws.service=bitwarden-ws"
#      - "traefik.http.services.bitwarden-ws.loadbalancer.server.port=3012"
