---

# docker-compose up  -d     # Run in detached mode

version: '3.3'

services:

  mongo:
    container_name: mongodb
    ports:
      - "27017:27017"
    image: mongo:4.4.3
    restart: always
    volumes:
      - ./mongodb_data:${DATA_DIR}/db