
include .env
export

# Define recipe to generate hostfile
.PHONY: hostfile
hostfile: #TODO: add support for multiple ips and extract ips from ifconfig
	@echo "# Content below generated by: make hostfile"
	@DIRS=$$(find ./apps -name 'docker-compose.yml' | xargs -I {} dirname {} | xargs -I {} basename {}); \
    for dir in $$DIRS; do \
        echo 127.0.0.1\\t\\t$$dir.$$DOMAINNAME; \
    done
