
include .env
export


# Define recipe to generate hostfile
.PHONY: hosts
hosts: #TODO: add support for multiple ips and extract ips from ifconfig
	@echo "# Content below generated by: make hosts"
	@DIRS=$$(find ./apps -name 'docker-compose.yml' | xargs -I {} dirname {} | xargs -I {} basename {}); \
    for dir in $$DIRS; do \
        echo 127.0.0.1\\t\\t$$dir.$$DOMAINNAME; \
    done


.PHONY: start
.ONESHELL:
start:

	@ALL_FILES=$$(find . -name 'docker-compose.yml' | awk '{print "-f "$$0}' | tr "\n" " ");
	#@echo $$ALL_FILES
	docker compose --env-file .env $$(echo $$ALL_FILES) up -d --build


.PHONY: stop
.ONESHELL:
stop:
	@export ADMIN_USER_GLOBAL="NONE"

	@export ADMIN_PASS_GLOBAL="NONE"

	@ALL_FILES=$$(find . -name 'docker-compose.yml' | awk '{print "-f "$$0}' | tr "\n" " ");

	docker compose --env-file .env $$(echo $$ALL_FILES) down

