# https://github.com/Cloudstek/docker-haproxy/blob/master/docker-compose.yml

services:
  haproxy:
    image: haproxy:3.2.0-alpine
    container_name: haproxy
#    hostname: mail.abassel.com
    restart: "no"
    user: haproxy
    environment:
      - SMTP_SERVER=$SMTP_SERVER
    ports:
      - "8404:8404"
      - "25:25"
      - "465:465"
    volumes:
      - ${PWD}/apps/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - no_internet
      - web
