# https://sensorsiot.github.io/IOTstack/

# https://docs.linuxserver.io/images/docker-nextcloud

---

networks:
  no_internet_db:
    name: no_internet_db
    driver: bridge
    internal: true # Block internet access

services:

  dbnc:
    image: mariadb:11.7
    restart: $RESTART
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: dbnc
    hostname: dbnc
    volumes:
      - ${APP_DATA_DIR}/nextcloud_db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_ROOT_PASSWORD=$ADMIN_PASS_GLOBAL
      - MYSQL_ROOT_PASSWORD=$ADMIN_PASS_GLOBAL
      - MYSQL_PASSWORD=$ADMIN_PASS_GLOBAL
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=$ADMIN_USER_GLOBAL
    networks:
      - no_internet_db

  nextcloud:
    image: nextcloud:31.0.2   #lscr.io/linuxserver/nextcloud:latest
    restart: $RESTART
    container_name: nextcloud
    depends_on:
      - dbnc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

#     https://github.com/nextcloud/docker

      - MYSQL_PASSWORD=$ADMIN_PASS_GLOBAL
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=$ADMIN_USER_GLOBAL
      - MYSQL_HOST=dbnc

      # WebDav file sync will refuse to work because internally we use http inside docker-compose
      - OVERWRITEPROTOCOL=https

#      - ServerName=$HTTP_SCHEMA://nextcloud.$DOMAINNAME
#      - NEXTCLOUD_ADMIN_USER=$ADMIN_USER_GLOBAL
#      - NEXTCLOUD_ADMIN_PASSWORD=$ADMIN_PASS_GLOBAL

    volumes:
      - ${APP_DATA_DIR}/nextcloud/data:/var/www/html/data
      - ${APP_DATA_DIR}/nextcloud/apps:/var/www/html/custom_apps
      - ${APP_DATA_DIR}/nextcloud/config:/var/www/html/config


# https://geek-cookbook.funkypenguin.co.nz/recipes/nextcloud/
#    ports:
#      - 443:443
#    restart: unless-stopped
    networks:
      - no_internet
      - no_internet_db
    labels:

      - "homepage.group=Services"
      - "homepage.name=nextcloud"
      - "homepage.icon=nextcloud.png"  # https://github.com/walkxcode/dashboard-icons
      - "homepage.href=$HTTP_SCHEMA://nextcloud.$DOMAINNAME/"
      - "homepage.description=Nextcloud"

      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.$DOMAINNAME`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
