

# https://www.cloudbees.com/blog/how-to-install-and-run-jenkins-with-docker-compose

version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:2.375.3-lts
    privileged: true
    restart: $RESTART
    user: root
#    ports:
#      - 8080:8080
#      - 50000:50000
    container_name: jenkins
    volumes:
      - $APP_DATA_DIR/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - no_internet
    labels:

      - "homepage.group=Services"
      - "homepage.name=Jenkins"
      - "homepage.icon=jenkins.png"  # https://github.com/walkxcode/dashboard-icons
      - "homepage.href=$HTTP_SCHEMA://jenkins.$DOMAINNAME/"
      - "homepage.description=Jenkins"

      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
