# https://www.cloudbees.com/blog/how-to-install-and-run-jenkins-with-docker-compose

services:
  jenkins:
    image: jenkins  #jenkins/jenkins:2.387.1-lts
    build:
      dockerfile: ${PWD}/apps/jenkins/Dockerfile
    privileged: true
    restart: $RESTART
    user: root
#    ports:
#      - 8080:8080
#      - 50000:50000
    container_name: jenkins
    volumes:
      - $APP_DATA_DIR/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # required for builds to work
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - no_internet
      - web  # required for builds to work
    labels:

      - "homepage.group=Services"
      - "homepage.name=Jenkins"
      - "homepage.icon=jenkins.png"  # https://github.com/walkxcode/dashboard-icons
      - "homepage.href=$HTTP_SCHEMA://jenkins.$DOMAINNAME/"
      - "homepage.description=Jenkins"

      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.$DOMAINNAME`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
