---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true

target: _self # Possible options include _blank, _self, and _top

color: slate

background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80

layout:
  Services:
    style: row
    columns: 4
