version: "3.3"

services:

  traefik:
    image: "traefik:v2.9.6"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web
      - no_internet

networks:
  no_internet:
    name: no_internet
    driver: bridge
    internal: true # Block internet access
  web:
    name: web
    driver: bridge
