services:

  traefik:
    image: "traefik:3.5.0"
    container_name: "traefik"
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=no_internet"
      - "--providers.docker.defaultRule=Host(`traefik.$DOMAINNAME`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.ssh.address=:2222"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"

      # https://community.home-assistant.io/t/how-to-give-traefik-access-to-ha-with-ha-in-network-mode-host-on-the-same-machine-in-docker/458379
      # Generate certs
      - "--certificatesresolvers.le.acme.email=$CLOUDFLARE_EMAIL"
      # https://williamhayes.medium.com/traefik-letsencrypt-and-acme-json-configuration-problems-5780c914351d
      - "--certificatesresolvers.le.acme.storage=/shared/acme.json"
      - "--certificatesresolvers.le.acme.dnsChallenge=true"
      - "--certificatesResolvers.le.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesResolvers.le.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
#      - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # DEBUG TEST
      - "--entrypoints.websecure.http.tls.certResolver=le"

    environment:
      # https://go-acme.github.io/lego/dns/cloudflare/
      - CF_API_EMAIL=$CLOUDFLARE_EMAIL
      - CF_DNS_API_TOKEN=$CLOUDFLARE_API_KEY

    labels:
      - "homepage.group=Services"
      - "homepage.name=Traefik"
      - "homepage.icon=traefik.png"  # https://github.com/walkxcode/dashboard-icons
      - "homepage.href=$HTTP_SCHEMA://traefik.$DOMAINNAME/"
      - "homepage.description=Traefik Dashboard"

      - "traefik.enable=true"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.routers.traefik.rule=Host(`traefik.$DOMAINNAME`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

      # Wildcard cert
      - "traefik.http.routers.traefik.tls.domains[0].main=$DOMAINNAME"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.$DOMAINNAME"
      - "traefik.http.routers.traefik.tls.certresolver=le"

    ports:
      - "80:80"
#      - "8080:8080"
      - "443:443"
      - "2222:2222"  # ssh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # https://williamhayes.medium.com/traefik-letsencrypt-and-acme-json-configuration-problems-5780c914351d
      - ${APP_DATA_DIR}/traefik2/shared:/shared
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - web
      - no_internet

networks:
  no_internet:
    name: no_internet
    driver: bridge
    internal: true # Block internet access
  web:
    name: web
    driver: bridge
