# Run this docker individually

# Test variables/configuration
# ADMIN_USER_GLOBAL=<USERNAME> ADMIN_PASS_GLOBAL=<PASSWORD> docker-compose config

# Up
# ADMIN_USER_GLOBAL=<USERNAME> ADMIN_PASS_GLOBAL=<PASSWORD> docker-compose up  -d  --build   # Run in detached mode

services:

  mongo:
    image: mongo:5.0.6-focal
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ${APP_DATA_DIR}/mongodb:/data/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ADMIN_USER_GLOBAL}
      - MONGO_INITDB_ROOT_PASSWORD=${ADMIN_PASS_GLOBAL}
    networks:
      - no_internet
